version: "3.9"
services:
  task_distributor:
    build: ./task_distributor
    ports:
      - "5000:5000"

  load_balancer:
    build: ./load_balancer
    ports:
      - "5555:5555"
      - "5556:5556"

  worker1:
    build: ./worker
    environment:
      - WORKER_NAME=Worker1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - model:/tmp/model
    depends_on:
      - load_balancer

  worker2 :
    build: ./worker
    environment:
      - WORKER_NAME=Worker2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - model:/tmp/model
    depends_on:
      - load_balancer

volumes:
  model:
